In [1]:
import numpy as np
import math
from copy import deepcopy

In [2]:
A = np.array([[3, -0.7, -1, 0.3], [-0.7, 4, 0.5, 1], [-1, 0.5, 4, 0.5], [0.2, 1, 0.5, 3]])

In [3]:
A

array([[ 3. , -0.7, -1. ,  0.3],
       [-0.7,  4. ,  0.5,  1. ],
       [-1. ,  0.5,  4. ,  0.5],
       [ 0.2,  1. ,  0.5,  3. ]])

In [4]:
b = np.array([1, 1.5, 1.75, 1.5])

In [5]:
b

array([1.  , 1.5 , 1.75, 1.5 ])

In [63]:
def yacob(x0, A, b, eps):
    x_old = deepcopy(x0)
    x_new = deepcopy(x0)
    k = 1
    while True:
        for i in range(A.shape[0]):
            x_new[i] = float(np.sum([- A[i][j] / A[i][i] * x_old[j] for j in range(A.shape[1])] + [1 * x_old[i], b[i] / A[i][i]]))
        print(f'it: {k} {x_new}')
        print(f"A * x =", np.dot(A, x_new))
        if k == 1:
            print(f'norm of vector(|| x[{k}] - x[{k-1}]||) = {np.linalg.norm(x_new - x_old)}')
        if np.linalg.norm(x_new - x_old) < eps:
            print(f'norm of vector(|| x[{k}] - x[{k-1}]||) = {np.linalg.norm(x_new - x_old)}')
            return x_new
        
        x_old = deepcopy(x_new)
        k += 1

In [64]:
x0 = np.array([0, 0, 0, 0], dtype=np.float32)

In [65]:
yacob(x0, A, b, 0.0001)

it: 1 [0.33333334 0.375      0.4375     0.5       ]
A * x = [0.45000003 1.98541666 1.85416666 2.16041667]
norm of vector(|| x[1] - x[0]||) = 0.8325517177581787
it: 2 [0.51666665 0.25364584 0.41145834 0.27986112]
A * x = [1.04494786 1.13850699 1.3959202  1.40229171]
it: 3 [0.501684   0.3440191  0.4999783  0.31243056]
A * x = [0.85798953 1.58731725 1.82645403 1.63163672]
it: 4 [0.5490208  0.32218978 0.4808648  0.26855165]
A * x = [1.02123034 1.41342858 1.66980906 1.47808128]
it: 5 [0.541944   0.34383264 0.50091255 0.2758579 ]
A * x = [0.96699405 1.52228392 1.77155143 1.53025141]
it: 6 [0.55294603 0.33826166 0.4955247  0.2657741 ]
A * x = [1.00626245 1.47952089 1.73117067 1.49393553]
it: 7 [0.55085856 0.34338143 0.50023204 0.2677956 ]
A * x = [0.9923153  1.50583636 1.75565812 1.50705594]
it: 8 [0.5534201  0.34192234 0.4988175  0.26544362]
A * x = [1.00173032 1.49514766 1.74553287 1.49834599]
it: 9 [0.55284333 0.34313542 0.4999343  0.26599497]
A * x = [0.99819941 1.50151344 1.751459   1.50

array([0.55342317, 0.34299287, 0.49978298, 0.26546708], dtype=float32)

In [66]:
def seidel(x0, A, b, eps):
    x_old = deepcopy(x0)
    x_new = deepcopy(x0)
    k = 1
    while True:
        for i in range(A.shape[0]):
            x_new[i] = float(np.sum([- A[i][j] / A[i][i] * x_new[j] for j in range(i)] +
                                    [- A[i][j] / A[i][i] * x_old[j] for j in range(i, A.shape[1])] +  [1 * x_old[i], b[i] / A[i][i]]))
        print(f'it: {k} {x_new}')
        print(f"A * x =", np.dot(A, x_new))
        if k == 1:
            print(f'norm of vector(|| x[{k}] - x[{k-1}]||) = {np.linalg.norm(x_new - x_old)}')
        if np.linalg.norm(x_new - x_old) < eps:
            print(f'norm of vector(|| x[{k}] - x[{k-1}]||) = {np.linalg.norm(x_new - x_old)}')
            return x_new
        x_old = deepcopy(x_new)
        k += 1

In [67]:
seidel(x0, A, b, 0.0001)

it: 1 [0.33333334 0.43333334 0.46666667 0.25555554]
A * x = [0.30666669 1.98888888 1.87777777 1.49999996]
norm of vector(|| x[1] - x[0]||) = 0.7628730535507202
it: 2 [0.5644444  0.35155556 0.5027222  0.26139817]
A * x = [1.02294163 1.5238704  1.75292125 1.50000004]
it: 3 [0.5567972 0.3442497 0.5009933 0.2646314]
A * x = [1.00781294 1.50236878 1.75161658 1.49999996]
it: 4 [0.5541929  0.34320176 0.5000691  0.26530838]
A * x = [1.0018609  1.50021492 1.75033849 1.50000002]
it: 5 [0.5535726  0.34303948 0.49984968 0.26544037]
A * x = [1.00037258 1.50002233 1.75006604 1.49999996]
it: 6 [0.5534484  0.34301215 0.49980554 0.26546514]
A * x = [1.00007063 1.50000266 1.75001243 1.50000002]
it: 7 [0.55342484 0.34300736 0.49979714 0.2654697 ]
A * x = [1.00001313 1.50000031 1.75000224 1.49999999]
norm of vector(|| x[7] - x[6]||) = 2.5860346795525402e-05


array([0.55342484, 0.34300736, 0.49979714, 0.2654697 ], dtype=float32)

In [38]:
def inv_mat(A):
    n = A.shape[0]
    I = np.identity(n)
    M = np.concatenate((A, I), axis=1)
    det = 1
    for i in range(0, n):
        pivot = M[i][i]
        row = M[i]
        det *= pivot
        M[i] = row / pivot
        for j in [k for k in range(0, n) if k != i]:
        # subtract current row from remaining rows
            M[j] = M[j] - M[i] * M[j][i]

  # extract inverse matrix
        inverse = M[:, n:]
    
    return inverse, det

In [45]:
#EXPLORATION

In [46]:
A

array([[ 3. , -0.7, -1. ,  0.3],
       [-0.7,  4. ,  0.5,  1. ],
       [-1. ,  0.5,  4. ,  0.5],
       [ 0.2,  1. ,  0.5,  3. ]])

In [49]:
inv_A, det = inv_mat(A)

In [50]:
inv_A

array([[ 0.38904309,  0.07598853,  0.09782955, -0.08053875],
       [ 0.07257587,  0.28902944, -0.00514174, -0.10274378],
       [ 0.09646449, -0.00455021,  0.28156709, -0.05505756],
       [-0.06620558, -0.10065068, -0.05173591,  0.38212677]])

In [51]:
def p2_mat_norm(A):
    M = np.dot(A, A.T)
    w, v = np.linalg.eig(M)
    max_w = np.max(w)
    return np.sqrt(max_w)

In [52]:
norm_A = p2_mat_norm(A)
print(norm_A)

5.452729686790202


In [53]:
norm_inv_A = p2_mat_norm(inv_A)
print(norm_inv_A)

0.556576660002211


In [55]:
cond = norm_A * norm_inv_A
print(cond)

3.034862076968593
